batch_size: 1
checkpoint: true
ckpt_freq: 100
data:
  data: ''
  eval_instruct_data: /home/luca/data/verify.jsonl
  instruct:
    dynamic_chunk_fn_call: true
    shuffle: true
  instruct_data: /home/luca/data/finetune.jsonl
  shuffle: false
eval_freq: 100
log_freq: 1
lora:
  dropout: 0.0
  enable: true
  rank: 64
  scaling: 2.0
max_norm: 1.0
max_steps: 300
mlflow:
  experiment_name: null
  tracking_uri: null
model_id_or_path: /home/luca/models/mistral/7B
no_ckpt: false
no_eval: false
num_ckpt_keep: 3
num_microbatches: 1
optim:
  lr: 6.0e-05
  pct_start: 0.05
  weight_decay: 0.1
run_dir: run_dir
save_adapters: true
seed: 0
seq_len: 32768
wandb:
  key: null
  offline: false
  project: null
  run_name: null
world_size: 1
